type Option = {
    id: number;
    name: string;
  };
  
 export const options: Option[] = [
    { id: 440, name: 'ASTON MARTIN' },
    { id: 441, name: 'TESLA' },
    { id: 442, name: 'JAGUAR' },
    { id: 443, name: 'MASERATI' },
    { id: 445, name: 'ROLLS-ROYCE' },
    { id: 448, name: 'TOYOTA' },
    { id: 449, name: 'MERCEDES-BENZ' },
    { id: 452, name: 'BMW' },
    { id: 454, name: 'BUGATTI' },
    { id: 456, name: 'MINI' },
    { id: 460, name: 'FORD' },
    { id: 464, name: 'LINCOLN' },
    { id: 465, name: 'MERCURY' },
    { id: 466, name: 'LOTUS' },
    { id: 467, name: 'CHEVROLET' },
    { id: 468, name: 'BUICK' },
    { id: 469, name: 'CADILLAC' },
    { id: 470, name: 'HOLDEN' },
    { id: 471, name: 'OPEL' },
    { id: 472, name: 'GMC' },
    { id: 473, name: 'MAZDA' },
    { id: 474, name: 'HONDA' },
    { id: 475, name: 'ACURA' },
    { id: 476, name: 'DODGE' },
    { id: 477, name: 'CHRYSLER' },
    { id: 478, name: 'NISSAN' },
    { id: 480, name: 'INFINITI' },
    { id: 481, name: 'MITSUBISHI' },
    { id: 482, name: 'VOLKSWAGEN' },
    { id: 485, name: 'VOLVO' },
    { id: 492, name: 'FIAT' },
    { id: 493, name: 'ALFA ROMEO' },
    { id: 497, name: 'LANCIA' },
    { id: 498, name: 'HYUNDAI' },
    { id: 499, name: 'KIA' },
    { id: 502, name: 'LAMBORGHINI' },
    { id: 504, name: 'SMART' },
    { id: 509, name: 'SUZUKI' },
    { id: 515, name: 'LEXUS' },
    { id: 523, name: 'SUBARU' },
    { id: 533, name: 'MAYBACH' },
    { id: 539, name: 'MORGAN' },
    { id: 542, name: 'ISUZU' },
    { id: 565, name: 'TRIUMPH' },
    { id: 572, name: 'SAAB' },
    { id: 582, name: 'AUDI' },
    { id: 583, name: 'BENTLEY' },
    { id: 584, name: 'PORSCHE' },
    { id: 603, name: 'FERRARI' },
    { id: 606, name: 'AM GENERAL' },
    { id: 629, name: 'CREATIVE COACHWORKS' },
    { id: 771, name: 'AC PROPULSION' },
    { id: 847, name: 'DAIHATSU' },
    { id: 972, name: 'FALCON' },
    { id: 986, name: 'EV INNOVATIONS' },
    { id: 992, name: 'FAW JIAXING HAPPY MESSENGER' },
    { id: 1056, name: 'SATURN' },
    { id: 1077, name: 'DAEWOO' },
    { id: 1124, name: 'AMERICAN MOTORS' },
    { id: 1142, name: 'FORMULA 1 STREET COM' },
    { id: 1146, name: 'GEO' },
    { id: 1151, name: 'FORTUNESPORT VES' },
    { id: 1288, name: 'AAS' },
    { id: 1292, name: 'EQUUS AUTOMOTIVE' },
    { id: 1393, name: 'ELECTRIC MOBILE CARS' },
    { id: 1498, name: 'AVERA MOTORS' },
    { id: 1683, name: 'BAKKURA MOBILITY' },
    { id: 1755, name: 'TH!NK' },
    { id: 1777, name: 'CODA' },
    { id: 1869, name: 'CONTEMPORARY CLASSIC CARS (CCC)' },
    { id: 1896, name: 'KOENIGSEGG' },
    { id: 1991, name: 'BYD' },
    { id: 2018, name: 'KANDI' },
    { id: 2049, name: 'KEPLER MOTORS' },
    { id: 2131, name: 'MAKING YOU MOBILE' },
    { id: 2236, name: 'MCLAREN' },
    { id: 2376, name: 'MYCAR' },
    { id: 2408, name: 'EAGLE' },
    { id: 2409, name: 'PLYMOUTH' },
    { id: 2665, name: 'NJD AUTOMOTIVE LLC' },
    { id: 2745, name: 'PHOENIX MOTORCARS' },
    { id: 3176, name: 'ROCKET SLED MOTORS' },
    { id: 3440, name: 'VISION INDUSTRIES' },
    { id: 3540, name: 'WARHAWK PERFORMANCE' },
    { id: 3583, name: 'UKEYCHEYMA' },
    { id: 3706, name: 'TOTAL ELECTRIC VEHICLES' },
    { id: 3766, name: 'SPYKER' },
    { id: 4162, name: 'OLDSMOBILE' },
    { id: 4220, name: 'PANOZ' },
    { id: 4355, name: 'SALEEN' },
    { id: 4410, name: 'SOLECTRIA' },
    { id: 4451, name: 'YESTER YEAR AUTO' },
    { id: 4596, name: 'BXR' },
    { id: 4634, name: 'ENGINE CONNECTION' },
    { id: 4644, name: 'BLUECAR' },
    { id: 4764, name: 'MOSLER' },
    { id: 4767, name: 'PAGANI' },
    { id: 4859, name: 'REVOLOGY' },
    { id: 5015, name: 'EMA' },
    { id: 5042, name: 'COSTIN SPORTS CAR' },
    { id: 5083, name: 'GENESIS' },
    { id: 5122, name: 'KARMA' },
    { id: 5208, name: 'MATRIX MOTOR COMPANY' },
    { id: 5367, name: 'ARMBRUSTER STAGEWAY' },
    { id: 5381, name: 'LUMEN' },
    { id: 5464, name: 'ASUNA' },
    { id: 5468, name: 'MERKUR' },
    { id: 5552, name: 'AVANTI' },
    { id: 5553, name: 'YUGO' },
    { id: 5554, name: 'PEUGEOT' },
    { id: 5555, name: 'STERLING MOTOR CAR' },
    { id: 5557, name: 'CONSULIER GTP' },
    { id: 5657, name: 'DATSUN' },
    { id: 5661, name: 'PININFARINA' },
    { id: 5760, name: 'VINTAGE AUTO' },
    { id: 5767, name: 'LONDONCOACH INC' },
    { id: 5848, name: 'MGS GRAND SPORT (MARDIKIAN)' },
    { id: 5938, name: 'PANTHER' },
    { id: 6018, name: 'DAYTONA COACH BUILDERS' },
    { id: 6069, name: 'UCC' },
    { id: 6263, name: 'RS SPIDER' },
    { id: 6264, name: 'GRUPPE B' },
    { id: 6265, name: 'RALLY SPORT' },
    { id: 6313, name: 'RENAISSANCE' },
    { id: 6364, name: 'JAC 427' },
    { id: 6408, name: 'HUNTER DESIGN GROUP, LLC' },
    { id: 6473, name: 'BLACKWATER' },
    { id: 6663, name: 'GULLWING INTERNATIONAL MOTORS, LTD.' },
    { id: 6759, name: 'AMERITECH CORPORATION' },
    { id: 6792, name: 'STANFORD CUSTOMS' },
    { id: 6880, name: 'CLASSIC ROADSTERS' },
    { id: 6986, name: 'HERITAGE' },
    { id: 7099, name: 'COBRA CARS' },
    { id: 7207, name: 'C-R CHEETAH RACE CARS' },
    { id: 7225, name: 'PAS' },
    { id: 7425, name: 'BUG MOTORS' },
    { id: 7477, name: 'EXCALIBUR AUTOMOBILE CORPORATION' },
    { id: 7765, name: 'IVES MOTORS CORPORATION (IMC)' },
    { id: 7836, name: 'AUTODELTA USA INC' },
    { id: 8395, name: 'AUTOCAR LTD' },
    { id: 8549, name: 'MOKE' },
    { id: 8605, name: 'BBC' },
  ];
  
const generateYears = (start: number, end: number): number[] => {
    const years: number[] = [];
    for (let year = start; year <= end; year++) {
        years.push(year);
    }
    return years;
};
  
export const years = generateYears(2015, 2024);